node{

    def dockerImage = "mamat08nurahmat/chatbotwa-webhook:$BUILD_NUMBER"
    stage('Source Checkout'){        
        git 'https://github.com/mamat08nurahmat/chatbotwa-webhook'
    }
    
    
    stage('Build Docker Image'){
        sh "docker build -t ${dockerImage} ."
    }
    
    stage('Push DockerHub'){
		withCredentials([string(credentialsId: 'docker-hub', variable: 'dockerhubPwd')]) {
			sh "docker login -u mamat08nurahmat -p ${dockerhubPwd}"
		}
        
        sh "docker push ${dockerImage}"
    }
    
    stage('Deploy To Production'){
	    
    sh "bash rolling_update.sh $BUILD_NUMBER"
	sh "curl 13.68.230.107 "
	
// 		def dockerRun = "docker run -d -p 8080:8080 --name nodeapp ${dockerImage}"
// 		sshagent(['dev-docker']) {
// 		    try{
// 				sh "ssh -o StrictHostKeyChecking=no ec2-user@13.127.166.0 docker rm -f nodeapp "
// 			}catch(e){
			
			
// 			}
// 			sh "ssh  ec2-user@13.127.166.0 ${dockerRun}"
// 		}
		
	}
}
